#!/bin/sh

# Install silently from installer app.
"$3/private/tmp/Tracker-osx-installer.app/Contents/MacOS/osx-x86_64" --mode unattended
rc=$?

# Remove installer app.
/bin/rm -r "$3/private/tmp/Tracker-osx-installer.app"

exit $rc
